version: '3.8'

services:
  app:
    build: .
    container_name: song_service
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
